#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

ln -sf $DOTFILES/lazygit/config.yml $HOME/.config/lazygit/config.yml

mkdir -p $HOME/.local/bin

ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

git config --global core.editor nvim
